werf:
  repo: ui-vmm/ui-vmm-panel

global:
  env: ""
  _includes:
    apps-ingresses-defaultIngress:
      class:
        _default: "nginx"

    apps-stateless-defaultApp:
      revisionHistoryLimit: 3
      containers:
        main:
          enabled: true
      service:
        enabled: true
        name: "{{ $.CurrentApp.name }}"

apps-stateless:
  ui-vmm-panel:
    _include: ["apps-stateless-defaultApp"]
    enabled: true
    replicas: 3
    containers:
      main:
        image:
          name: uivmm/ui-vmm-panel
          staticTag: 0.1
        ports: |
          - name: http
            containerPort: 80
        livenessProbe: |
          httpGet:
            path: /healthz
            port: 80
          timeoutSeconds: 5
        configFiles:
          config.yml:
            mountPath: /etc/nginx/conf.d/default.conf
            content: |
              log_format combined_plus escape=json '{"time_local": "$time_local", '
                                       '"request_id": "$request_id", '
                                       '"remote_addr": "$remote_addr", '
                                       '"remote_user": "$remote_user", '
                                       '"request": "$request", '
                                       '"status": $status, '
                                       '"body_bytes_sent": "$body_bytes_sent", '
                                       '"request_time": $request_time, '
                                       '"http_referrer": "$http_referer", '
                                       '"http_user_agent": "$http_user_agent"}';
              server {
                listen 80;
                location / {
                  access_log /dev/stdout combined_plus;
                  index  index.html index.htm;
                  root   /usr/share/nginx/html;
                  try_files $uri /index.html;
                }
                error_page   500 502 503 504  /50x.html;
                location = /50x.html {
                  root   /usr/share/nginx/html;
                }
                location ~* .(css|eot|ico|js|json|map|png|svg|ttf|txt|woff|woff2)$ {
                  access_log off;
                  root   /usr/share/nginx/html;
                }
                location /healthz {
                  access_log off;
                  return 200;
                }
              }
    service:
      ports: |
        - name: http
          port: 80

apps-ingresses:
  ui-vmm-panel:
    _include: ["apps-ingresses-defaultIngress"]
    enabled: true
    host: "{{ $.Values.global.ci_url }}"
    paths: |
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-vmm-panel
            port:
              number: 80
